version: "3.2"

services:

  names.service:
    container_name: wb.names.service
    image: 357210185381.dkr.ecr.us-east-1.amazonaws.com/wormbase/names:${WB_NAMES_RELEASE}
    ports:
      - "80:3000"
    env_file:
      - .env
